pipeline:
  name: Krishika_GitHealth_page
  identifier: Krishika_GitHealth_page
  projectIdentifier: krishika_test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Krishika_test_connector
        build: <+input>
  stages:
    - stage:
        name: krishika_test
        identifier: krishika_test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo hel
                      lo 
                      echo hey
    - stage:
        name: krishika_stage2
        identifier: krishika_stage2
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo helloworld2
