pipeline:
  name: harnessPipeline
  identifier: harnessPipeline
  projectIdentifier: krishika_test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Krishika_test_connector
        build: <+input>
  stages:
    - stage:
        name: pie
        identifier: pie
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo hello
